"""empty message

Revision ID: 18f4823b7334
Revises: 82fe5e5e3aa8
Create Date: 2024-07-04 17:48:09.378314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f4823b7334'
down_revision = '82fe5e5e3aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
