"""empty message

Revision ID: 520eaea1ff8e
Revises: 1cd1c6abf742
Create Date: 2024-07-04 15:13:23.027277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520eaea1ff8e'
down_revision = '1cd1c6abf742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
