"""empty message

Revision ID: 6e69be71279d
Revises: a2b3d98b64d1
Create Date: 2024-07-04 23:50:19.537196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e69be71279d'
down_revision = 'a2b3d98b64d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('phone_no')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_no')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_no', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
