"""empty message

Revision ID: 82fe5e5e3aa8
Revises: 520eaea1ff8e
Create Date: 2024-07-04 17:15:28.889898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fe5e5e3aa8'
down_revision = '520eaea1ff8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
