"""empty message

Revision ID: a2b3d98b64d1
Revises: 18f4823b7334
Create Date: 2024-07-04 23:30:49.350837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3d98b64d1'
down_revision = '18f4823b7334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=10), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_no', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_no')
        batch_op.drop_column('email')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
